apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: castai-cluster-controller
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "castai-agent.labels" . | nindent 4 }}
value: 1000000000
description: "Used for CAST AI cluster-controller components."
